name: rippledb
description: A sample command-line application.
version: 0.0.1+1
homepage: https://github.com/imatheus-lucas/rippledb
repository: https://github.com/imatheus-lucas/rippledb
issue_tracker: https://github.com/imatheus-lucas/rippledb/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.7"

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.7.7
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.38

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
