name: ripple
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1
  flutter: ^3.32.7

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.7.7
  # path: ^1.8.0
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
